[package]
name = "webview-official-sys"
version = "0.1.0"
authors = ["Ngo Iok Ui <wusyong9104@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1"
pkg-config = "0.3"